name: bonds_high_value_win_notifier
# run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
  schedule:
     - cron: "0 8 1 * *"
env:
  uv-version: "0.12.0"
  UV_SYSTEM_PYTHON: 1
jobs:
  build_execute:
    runs-on: ubuntu-latest
    outputs:
      results_path: ${{ steps.run_python.outputs.RESULTS_PATH }}
      message: ${{ steps.run_python.outputs.MESSAGE }}
      create_artifact: ${{ steps.run_python.outputs.CREATE_ARTIFACT }}
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          # Install a specific version of uv.
          version: ${{ env.uv-version }}
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Install dependencies with uv
        run: uv sync --locked --all-extras --dev

      - name: List pip packages
        run: pip list

      - name: Show env vars
        run: env
      
      - name: Run Python
        id: run_python ##Needed for referebce capabilities
        env:
          PB_VAL_OF_BOND: ${{ vars.PB_VAL_OF_BOND }}
          PB_DATE_OF_PURCHASE: ${{ vars.PB_DATE_OF_PURCHASE }}
          PB_AREA: ${{ vars.PB_AREA }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
        run: python src/main.py
      - name: Upload Results Artifact
        if: ${{ steps.run_python.outputs.CREATE_ARTIFACT == 'True' }}
        uses: actions/upload-artifact@v7
        with:
          name: winnings-results
          path: ${{ steps.run_python.outputs.RESULTS_PATH }}

  notify_if_win:
    needs: build_execute
    runs-on: ubuntu-latest
    env:
      message: ${{ needs.build_execute.outputs.message }}
      results_path: ${{ needs.build_execute.outputs.results_path }} ##Defaults to False if Upload Results Artifact is not ran, as per condition for RESULTS_PATH
      create_artifact: ${{ needs.build_execute.outputs.create_artifact }} ##Defaults to False if Upload Results Artifact is not ran, as per condition for CREATE_ARTIFACT
    steps:
      - uses: actions/download-artifact@v7
        if: ${{ env.create_artifact == 'True' }}
        with:
          name: winnings-results
      - name: Send mail
        uses: dawidd6/action-send-mail@v18
        with:
          # MailerSend Server specs
          server_address: ${{ vars.MAIL_ADDRESS }}
          server_port: ${{ vars.SERVER_PORT }}
          
          # Authentication
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          
          ## Email Routing Info
          subject: "Premium Bonds: High Value Winnings Monthly Filter Results"
          to: ${{ vars.MAIL_TO }} 
          from: ${{ vars.MAIL_FROM }}

          ## Attachments - Defaults to empty in case results path is Falsey
          attachments: ${{ env.results_path || '[]' }}
          
          ##Message Body

          body: | ##Multi-Line string reminder
           The results are in from this months Premium bonds high value earnings results!!

           ${{ env.message }}