name: bonds_high_value_win_notifier
# run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
env:
  python-version: 3.14
jobs:
  build_execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python
        env:
          PB_VAL_OF_BOND: "25000"
          PB_DATE_OF_PURCHASE: "2024-02-26"
          PB_AREA: "london"
        run: python main.py