name: bonds_high_value_win_notifier
# run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
env:
  python-version: 3.14
jobs:
  build_execute:
    runs-on: ubuntu-latest
    outputs:
      send_email: ${{ steps.run_python.outputs.SEND_EMAIL }} ## If Python skips or crashes, these evaluate to '' safely
      pretty_printed_result: ${{ steps.run_python.outputs.PRETTY_PRINTED_RESULT }} ## If Python skips or crashes, these evaluate to '' safely
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python
        id: run_python
        env:
          PB_VAL_OF_BOND: "25000"
          PB_DATE_OF_PURCHASE: "2024-02-26"
          PB_AREA: "london"
        run: python main.py

  notify_if_win:
    if: needs.build_execute.outputs.send_email == 'True'
    needs: build_execute
    runs-on: ubuntu-latest
    env:
      SEND_EMAIL: ${{ needs.build_execute.outputs.send_email || 'False' }}
      PRETTY_PRINTED_RESULT: ${{ needs.build_execute.outputs.pretty_printed_result || '[{}]' }}
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v18
        with:
          # MailerSend Server Specifications
          server_address: ${{ vars.MAIL_ADDRESS }}
          server_port: 587
          
          # Authentication fetched securely from Actions Secrets
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          
          # Email Routing Information
          subject: "High Value Winnings Filter Results"
          to: ${{ vars.MAIL_TO }} 
          
          from: ${{ vars.MAIL_FROM }}
          
          body: |
           "The results are in from this months Premium bonds high value earnings results. 
           ${{ env.PRETTY_PRINTED_RESULT }}"