name: GitHub Token Debugger
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  github_debugger:
    runs-on: ubuntu-latest
    steps:
      - name: Debug OIDC Claims
        uses: steve-todorov/oidc-debugger-action@v1
        with:
          audience: '${{ github.server_url }}/${{ github.repository }}'
